import '../styles/globals.css'
import '../styles/fonts.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Test Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/NotoSansKR-Black-Alphabetic.woff"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/NotoSansKR-Black-Alphabetic.woff2"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
